swagger: "2.0"
info:
  version: 1.0.0
  title: Simulation API
  description: An API for managing simulations within 3DSIM.
  termsOfService: https://3dsim.com
  contact:
    name: 3DSIM API Team
    email: support@3dsim.com
    url: https://3dsim.github.io
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: 3dsim.cloud.tyk.io
basePath: /simulation-api
schemes:
  - https
paths:
  /status:
    get:
      description: |
        Use this endpoint to check server status.
      operationId: status
  /materials:
    get:
      description: Get list of materials
      operationId: getMaterials
      security:
        - simulationSecurity:
          - read:materials
    post:
      description: Creates a new material for the organizationId specified
      operationId: addMaterial
      security:
        - simulationSecurity:
          - write:materials

  /materials/{id}:
    get:
      description: Returns a material based on a single ID
      operationId: findMaterialById
      security:
        - simulationSecurity:
          - read:materials

  /materials/{id}/archive:
    put:
      description: archives a single material based on the ID supplied
      operationId: archiveMaterial
      security:
        - simulationSecurity:
          - write:materials

  /machines:
    get:
      description: Get list of machines
      operationId: getMachineList
      security:
        - simulationSecurity:
          - read:machines

    post:
      description: Add a machine
      operationId: postMachine
      security:
        - simulationSecurity:
          - write:machines

  /machines/{id}:
    get:
      description: Get a machine
      operationId: getMachine
      security:
        - simulationSecurity:
          - read:machines

    put:
      description: Update a machine
      operationId: putMachine
      security:
        - simulationSecurity:
          - write:machines

  /machines/{id}/archive:
    put:
      description: Archive a machine, making it not available for use in a simulation (sets archived property to true)
      operationId: archiveMachine
      security:
        - simulationSecurity:
          - write:machines

  /machines/{id}/unarchive:
    put:
      description: Unarchive a machine, making it available for use in a simulation (sets archived property to false)
      operationId: unarchiveMachine
      security:
        - simulationSecurity:
          - write:machines

  /parts:
    get:
      description: Get list of parts
      operationId: getParts
      security:
        - simulationSecurity:
          - read:parts
    post:
      description: Adds a part and starts processing the part.  When processing is finished, the "availability" field
        for the part will change to "Available".  See GET /parts.
      operationId: addParts
      security:
        - simulationSecurity:
          - write:parts
    put:
      description: Updates a Part
      operationId: UpdatePart
      security:
        - simulationSecurity:
          - write:parts

  /parts/geometryuploadurl:
    get:
      description: Gets a time sensitive URL to upload a geometry file to AmazonS3.
      operationId: getNewPartGeometryUploadUrl
      security:
        - simulationSecurity:
          - write:parts

  /parts/{id}:
    get:
      description: Get a single part by Id
      operationId: getPart
      security:
        - simulationSecurity:
          - read:parts

  /parts/{id}/archive:
    put:
      description: Archive a Part. Archiving a part will set the status to archived and will exclude the part from get list requests. To unarchive a part call /parts/{id}, change the status and then /parts (put) to update.
      operationId: ArchivePart
      security:
        - simulationSecurity:
          - write:parts

  /parts/{id}/geometryurl:
    get:
      description: Gets a time sensitive URL to the geometry file stored in AmazonS3.
      operationId: getPartGeometryUrl
      security:
        - simulationSecurity:
          - read:parts

  /parts/{id}/geometry:
    get:
      description: Gets a list of triangles for the geometry file stored in AmazonS3.
      operationId: getPartGeometry
      security:
        - simulationSecurity:
          - read:parts

  /simulations:
    get:
      description: Gets a list of all simulations
      operationId: getSimulations
      security:
        - simulationSecurity:
          - read:simulations

  /simulations/{id}:
    get:
      description: Get a simulation
      operationId: getSimulation
      security:
        - simulationSecurity:
          - read:simulations
    patch:
      description: Patch a simulation
      operationId: patchSimulation
      security:
        - simulationSecurity:
          - write:simulations



  /porositysimulations:
    get:
      description: Gets a list of all porosity simulation
      operationId: getPorositySimulations
      security:
        - simulationSecurity:
          - read:simulations
    post:
      description: Posts a new porosity simulation
      operationId: postPorositySimulation
      security:
        - simulationSecurity:
          - write:simulations

  /porositysimulations/{id}:
    get:
      description: Get a porosity simulation
      operationId: getPorositySimulation
      security:
        - simulationSecurity:
          - read:simulations
    put:
      description: Puts an updated porosity simulation
      operationId: putPorositySimulation
      security:
        - simulationSecurity:
          - write:simulations

  /porositysimulations/{id}/cancel:
    put:
      description: Cancels a porosity simulation
      operationId: cancelPorositySimulation
      security:
        - simulationSecurity:
          - write:simulations
  /porositysimulations/{id}/start:
    put:
      description: Starts a porosity simulation.  If the simulation has been started before, start requests have no effect.
      operationId: startPorositySimulation
      security:
        - simulationSecurity:
          - write:simulations

  /singlebeadsimulations:
    get:
      description: Gets a list of all single bead simulations for the active user
      operationId: getSingleBeadSimulations
      security:
        - simulationSecurity:
          - read:simulations
    post:
      description: Posts a new single bead simulation
      operationId: postSingleBeadSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /singlebeadsimulations/{id}:
    get:
      description: Get a single bead simulation
      operationId: getSingleBeadSimulation
      security:
        - simulationSecurity:
          - read:simulations
    put:
      description: Puts an updated single bead simulation
      operationId: putSingleBeadSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /singlebeadsimulations/{id}/cancel:
    put:
      description: Cancels a single bead simulation
      operationId: cancelSingleBeadSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /singlebeadsimulations/{id}/start:
    put:
      description: Starts a single bead simulation.  If the simulation has been started before, start requests have no effect.
      operationId: startSingleBeadSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /thermalsimulations:
    get:
      description: Gets a list of all thermal simulations for the active user
      operationId: getThermalSimulations
      security:
        - simulationSecurity:
          - read:simulations
    post:
      description: Posts a new thermal simulation
      operationId: postThermalSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /thermalsimulations/{id}:
    get:
      description: Get a thermal simulation
      operationId: getThermalSimulation
      security:
        - simulationSecurity:
          - read:simulations
    put:
      description: Puts an updated thermal simulation
      operationId: putThermalSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /thermalsimulations/{id}/cancel:
    put:
      description: Cancels a thermal simulation
      operationId: cancelThermalSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /thermalsimulations/{id}/start:
    put:
      description: Starts a thermal simulation.  If the simulation has been started before, start requests have no effect.
      operationId: startThermalSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /scanpatternsimulations:
    get:
      description: Gets a list of all scan pattern simulations for the active user
      operationId: getScanPatternSimulations
      security:
        - simulationSecurity:
          - read:simulations
    post:
      description: Posts a new scan pattern simulation
      operationId: postScanPatternSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /scanpatternsimulations/{id}:
    get:
      description: Get a Scan Pattern simulation
      operationId: getScanPatternSimulation
      security:
        - simulationSecurity:
          - read:simulations
    put:
      description: Puts an updated scan pattern simulation
      operationId: putScanPatternSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /scanpatternsimulations/{id}/cancel:
    put:
      description: Cancels a Scan Pattern simulation
      operationId: cancelScanPatternSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /scanpatternsimulations/{id}/start:
    put:
      description: Starts a Scan Pattern simulation.  If the simulation has been started before, start requests have no effect.
      operationId: startScanPatternSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /assumedstrainsimulations:
    get:
      description: Gets a list of all assumed strain simulations for the active user
      operationId: getAssumedStrainSimulations
      security:
        - simulationSecurity:
          - read:simulations
    post:
      description: Posts a new assumed strain simulation
      operationId: postAssumedStrainSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /assumedstrainsimulations/{id}:
    get:
      description: Get a assumed strain simulation
      operationId: getAssumedStrainSimulation
      security:
        - simulationSecurity:
          - read:simulations
    put:
      description: Puts an updated assumed strain simulation
      operationId: putAssumedStrainSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /assumedstrainsimulations/{id}/cancel:
    put:
      description: Cancels a assumed strain simulation
      operationId: cancelAssumedStrainSimulation
      security:
        - simulationSecurity:
          - write:simulations

  /assumedstrainsimulations/{id}/start:
    put:
      description: Starts an assumed strain simulation.  If the simulation has been started before, start requests have no effect.
      operationId: startAssumedStrainSimulation
      security:
        - simulationSecurity:
          - write:simulations

securityDefinitions:
  simulationSecurity:
    type: oauth2
    authorizationUrl: https://3dsim.auth0.com/authorize
    flow: implicit
    scopes:
      write:simulations: create and update simulations
      read:simulations: read simulations
      write:parts: create and update parts
      read:parts: read parts
      write:machines: create and update machines
      read:machines: read machines
      write:materials: create and update materials
      read:materials: read materials
